[package]
name = "lm3s6965evb"
version = "0.1.0"
authors = ["n-k <nipunkumar@outlook.com>"]
edition = "2018"

[dependencies]
cortexm-threads = { path = "../.." }
cortex-m-semihosting = "0.3.2"
cortex-m = "0.5.8"
